feat(aws-apigw-http-api-lambda): implement Lambda authorizer with request handling and Terraform configuration

diff --git a/projects/aws-apigw-http-api-lambda/Makefile b/projects/aws-apigw-http-api-lambda/Makefile
--- a/projects/aws-apigw-http-api-lambda/Makefile
+++ b/projects/aws-apigw-http-api-lambda/Makefile
@@ -8,9 +8,18 @@ CGO_ENABLED=0
 # Garante que a pasta artifacts exista
 ensure-artifacts-dir:
 	@mkdir -p artifacts/worker
+	@mkdir -p artifacts/authorizer
 
 build: ensure-artifacts-dir
 	@echo "🔥 Building Worker (Monorepo Mode)..."
+
+	# --- Authorizer ---
+	@cd src/authorizer && \
+	GOOS=$(GOOS) GOARCH=$(GOARCH) CGO_ENABLED=$(CGO_ENABLED) \
+	go build -tags lambda.norpc -ldflags="-s -w" \
+	-o ../../artifacts/authorizer/bootstrap main.go
+
+	@cd artifacts/authorizer && zip -q -r ../authorizer.zip bootstrap
 
 	# --- Worker ---
 	@cd src/worker && \
@@ -38,10 +47,7 @@ deploy: build
 destroy:
 	@cd terraform && terraform destroy -auto-approve
 
-# --- NOVO TARGET DE TESTE ---
 test:
-	@echo "🚀 Getting API Endpoint from Terraform..."
-	@# O comando abaixo roda tudo em um único sub-shell para manter a var URL viva
 	@URL=$$(cd terraform && terraform output -raw api_endpoint); \
 	if [ -z "$$URL" ]; then \
 		echo "❌ Error: Terraform output 'api_endpoint' not found. Did you run 'make deploy'?"; \
@@ -53,3 +59,16 @@ test:
 	curl -s -X POST "$$URL/ingest" \
 		-H "Content-Type: application/json" \
 		-d '{"message": "Hello from Makefile"}' | jq . || echo "(Instale 'jq' para ver o JSON formatado)"
+test-auth:
+	@URL=$$(cd terraform && terraform output -raw api_endpoint); \
+	if [ -z "$$URL" ]; then \
+		echo "❌ Error: Terraform output 'api_endpoint' not found. Did you run 'make deploy'?"; \
+		exit 1; \
+	fi; \
+	echo "📡 Sending POST request to: $$URL/ingest-auth"; \
+	echo "📦 Payload: {\"message\": \"Hello from Makefile Autenticado!\"}"; \
+	echo "---------------------------------------------------"; \
+	curl -s -X POST "$$URL/ingest-auth" \
+		-H "Content-Type: application/json" \
+		-H "Authorization: Bearer alexandria-secret" \
+		-d '{"message": "Hello from Makefile Autenticado!"}' | jq . || echo "(Instale 'jq' para ver o JSON formatado)"
